### ISSUE TITLE
Make upload artifact step optional

### ISSUE THREAD

**Issue by yanndebray** [yanndebray/scheduled-task#4]
![image](https://github.com/yanndebray/scheduled-task/assets/128002745/c90968e5-2239-4ffd-aa0d-0a69f77a506a)

```yaml
    
      # Save the result as artifact
      - name: Archive output data
        uses: actions/upload-artifact@v4
        with:
          name: task-output
          path: 

```
